// <auto-generated />
using EFCore02;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426121807_Relation_Organizer_Profile")]
    partial class Relation_Organizer_Profile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore02.Modael.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("verifitedStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Organizers", (string)null);
                });

            modelBuilder.Entity("EFCore02.Modael.ProfilePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyWebsite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriganizrId")
                        .HasColumnType("int");

                    b.Property<string>("Short_biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OriganizrId")
                        .IsUnique();

                    b.ToTable("OrganizeProfile", (string)null);
                });

            modelBuilder.Entity("EFCore02.Modael.ProfilePage", b =>
                {
                    b.HasOne("EFCore02.Modael.Organizer", "Orgaizer")
                        .WithOne("OrgainzeProfile")
                        .HasForeignKey("EFCore02.Modael.ProfilePage", "OriganizrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orgaizer");
                });

            modelBuilder.Entity("EFCore02.Modael.Organizer", b =>
                {
                    b.Navigation("OrgainzeProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
