// <auto-generated />
using System;
using EFCore02;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426130719_Event-Registration")]
    partial class EventRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore02.Modael.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("BadgeId")
                        .IsUnique();

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("EFCore02.Modael.Badge", b =>
                {
                    b.Property<Guid>("BadgeNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("tier")
                        .HasColumnType("int");

                    b.HasKey("BadgeNum");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("EFCore02.Modael.Evient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxAttendees")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ParentId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("EFCore02.Modael.HomeAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomeAddresses");
                });

            modelBuilder.Entity("EFCore02.Modael.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("verifitedStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Organizers", (string)null);
                });

            modelBuilder.Entity("EFCore02.Modael.ProfilePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyWebsite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriganizrId")
                        .HasColumnType("int");

                    b.Property<string>("Short_biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OriganizrId")
                        .IsUnique();

                    b.ToTable("OrganizeProfile", (string)null);
                });

            modelBuilder.Entity("EFCore02.Modael.Registrations", b =>
                {
                    b.Property<int>("RegistrationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationsId"));

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvientId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegistrationsId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("EvientId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EFCore02.Modael.Attendee", b =>
                {
                    b.HasOne("EFCore02.Modael.HomeAddress", "HomeAddress")
                        .WithOne("Attendee")
                        .HasForeignKey("EFCore02.Modael.Attendee", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore02.Modael.Badge", "Badge")
                        .WithOne("Attendee")
                        .HasForeignKey("EFCore02.Modael.Attendee", "BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("HomeAddress");
                });

            modelBuilder.Entity("EFCore02.Modael.Evient", b =>
                {
                    b.HasOne("EFCore02.Modael.Organizer", "organizer")
                        .WithMany("Evients")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore02.Modael.Evient", null)
                        .WithMany("ParentEvent")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("organizer");
                });

            modelBuilder.Entity("EFCore02.Modael.ProfilePage", b =>
                {
                    b.HasOne("EFCore02.Modael.Organizer", "Orgaizer")
                        .WithOne("OrgainzeProfile")
                        .HasForeignKey("EFCore02.Modael.ProfilePage", "OriganizrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orgaizer");
                });

            modelBuilder.Entity("EFCore02.Modael.Registrations", b =>
                {
                    b.HasOne("EFCore02.Modael.Attendee", "Attendee")
                        .WithMany("Registrations")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore02.Modael.Evient", "Evient")
                        .WithMany("Registrations")
                        .HasForeignKey("EvientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Evient");
                });

            modelBuilder.Entity("EFCore02.Modael.Attendee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("EFCore02.Modael.Badge", b =>
                {
                    b.Navigation("Attendee")
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore02.Modael.Evient", b =>
                {
                    b.Navigation("ParentEvent");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("EFCore02.Modael.HomeAddress", b =>
                {
                    b.Navigation("Attendee")
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore02.Modael.Organizer", b =>
                {
                    b.Navigation("Evients");

                    b.Navigation("OrgainzeProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
